config/routes.rb
Rails.application.routes.draw do
  get 'tickets/new'
  get 'tickets/edit'
  get 'tickets/show'
  get 'projects/new'
  get 'projects/edit'
  get 'projects/show'
  get 'projects/index'
  get 'pages/demo'
  get 'pages/guest'
  patch 'tickets/update_hours/:id' => "tickets#update_hours", as: :update_hours_ticket
  patch 'tickets/close_ticket/:id' => "tickets#close_ticket", as: :close_ticket

  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :events, only: [ :new, :edit, :index ]
  end
  resources :projects, only: [ :create, :edit, :update, :show, :index ] do
    resources :events, only: [ :new ]
  end
  resources :tickets, only: [ :new, :edit, :show, :index, :create, :update ] do
    resources :memos
    resources :events, only: [ :new, :create ]
  end
  resources :working_tickets, only: [ :show, :index ]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-bugtracker">
  <%= link_to "HOME", root_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="btn custom-btn-nav toggle-btn",
        data-target="darkmode.toggle",
        data-action="click->darkmode#adjustBackground">
        <i class="far fa-moon"></i>
      </div>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "profile_picture.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_user.html.erb
<div class="navbar navbar-expand-sm navbar-user">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-inner-flex" id="navbarSupportedContent">
    <div>
      <ul class="navbar-nav mr-auto">
        <li>
          <div class="navbar-user-option btn custom-btn-nav toggle-btn",
            data-target="darkmode.toggle",
            data-action="click->darkmode#adjustBackground">
            <i class="far fa-moon button-darktheme"></i>
          </div>
        </li>
        <% if user_signed_in? %>
        <li class="link-navbar-user">
          <%= link_to "Dashboard", root_path, class: "link-navbar-user" %>
        </li>
        <li class="link-navbar-user">
          <%= link_to "Project list", projects_index_path, class: "link-navbar-user" %>
        </li>
        <li class="link-navbar-user">
          <%= link_to "Ticket list", tickets_path, class: "link-navbar-user" %>
        </li>

        <li class="link-navbar-user">
          <%= link_to "Profile", user_path(current_user), class: "link-navbar-user" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_ticket_list.html.erb
<ul>
  <% @tickets.each do |ticket|%>
    <li class="container-clickable-ticket">
      <%= link_to ticket_path(ticket) do %>
        <h3 class="text-caps">
          <%= ticket.title %>
          (<%= ticket.status %>)
        </h3>
        <p>
          <%= ticket.description   %>
        </p>
        <% if ticket.status == 'open' %>
          <% if ticket.ticket_age_in_hours == 0 %>
            <p>Opened less than an hour ago</p>
          <% elsif ticket.ticket_age_in_hours == 1 %>
            <p>Opened an hour ago</p>
          <% elsif ticket.ticket_age_in_hours <= 72 %>
            <p>Opened <%= ticket.ticket_age_in_hours %> hours ago</p>
          <% else %>
            <p>Opened <%= ticket.ticket_age_in_days %> days ago</p>
          <% end %>
        <% else %>
            <p><%= ticket.ticket_closing_date %></p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_working_feature.html.erb
<div class="container container-working-feature">
  <div>
    <h1>Currently no available on mobile devices.</h1>
    <p>However, you will be able to use our application in any device in a few days :)</p>
  </div>
</div>