config/routes.rb
Rails.application.routes.draw do
  get 'tickets/new'
  get 'tickets/edit'
  get 'tickets/show'
  get 'projects/new'
  get 'projects/edit'
  get 'projects/show'
  get 'projects/index'
  get 'pages/demo'
  get 'pages/guest'
  patch 'tickets/update_hours/:id' => "tickets#update_hours", as: :update_hours_ticket
  patch 'tickets/close_ticket/:id' => "tickets#close_ticket", as: :close_ticket

  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :events, only: [ :new, :edit, :index ]
  end
  resources :projects, only: [ :create, :edit, :update, :show, :index ] do
    resources :events, only: [ :new ]
  end
  resources :tickets, only: [ :new, :edit, :show, :index, :create, :update ] do
    resources :memos
    resources :events, only: [ :new, :create ]
  end
  resources :working_tickets, only: [ :show, :index ]
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  include ActiveModel::Dirty
  include TrackableWorkTime

  belongs_to :project
  has_many :memos
  has_many :events, as: :eventable

  validates :description, :priority, :status, :project_id,
            :title, presence: true

  def ticket_age_in_hours
    (Time.now - self.created_at).round / 60 / 60
  end

  def ticket_age_in_days
    (Time.now - self.created_at).round / 60 / 60 /24
  end

  def ticket_closing_date
    self.updated_at.strftime("Closed on %m/%d/%Y")
  end

  def identify_ticket_changes
    record = self.saved_changes
    changes = []
    changes << 'user' if record.has_key?('user_id')
    changes << 'status' if record.has_key?('status')
    changes << 'priority' if record.has_key?('priority')
    changes << 'category' if record.has_key?('category')
    changes
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = policy_scope(Ticket).order(created_at: :desc)
  end

  def new
    @ticket = Ticket.new
    @projects = Project.all.map {|project| [project.name, project.id]}
    authorize @ticket
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id
    authorize @ticket

    if @ticket.save
      event = Event.new(
        description: "Opened ticket #{@ticket.title}",
        user: current_user,
        eventable: @ticket,
        link: "/tickets/#{params[:ticket_id]}"
      )
      event.save
      redirect_to root_path
    else
      @errors = "#{@ticket.errors.messages}"

      render :new
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
    @users = User.all.map do |user|
      ["#{user.first_name} #{user.last_name}", user.id]
    end
    authorize @ticket
  end

  def close_ticket
    @ticket = Ticket.find(params[:id])
    authorize @ticket

    @ticket.end_timer if @ticket.active
    @ticket.update(status: 'closed')
    @ticket.save
    event = Event.new(
      description: "#{current_user.first_name} closed ticket #{@ticket.title}",
      user: current_user,
      eventable: @ticket,
      link: "/tickets/#{@ticket.id}"
    )
    event.save
    redirect_to ticket_path(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    authorize @ticket

    if @ticket.update(ticket_params)
      changes = Event.store_changes_record(@ticket.identify_ticket_changes)

      unless changes == "no changes"
        event = Event.new(
          description: "Changed the #{changes} on ticket #{@ticket.title}",
          user: current_user,
          eventable: @ticket,
          link: "/tickets/#{@ticket.id}"
        )
        event.save
      end
      redirect_to ticket_path(params[:id])
    else
      render :edit
    end
  end

  def update_hours
    @ticket = Ticket.find(params[:id])
    authorize @ticket

    if @ticket.active
      @ticket.end_timer
      redirect_to ticket_path(params[:id])
      current_user.working_ticket.destroy
    else
      @ticket.start_timer
      redirect_to ticket_path(params[:id])
      WorkingTicket.create(
        user: current_user,
        ticket: @ticket
      )
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
    ticket_user = User.where(id: @ticket.user_id).map
    @ticket_user = ticket_user.first
    @memo = Memo.new
    @memos = Memo.where(ticket_id: params[:id]).order(created_at: :desc)
    authorize @ticket
  end

  private

  def ticket_params
    params.require(:ticket).permit(:description, :project_id, :status,
    :priority, :category, :title, :user_id )
  end
end

app/views/tickets/_edit.html.erb
<h1>Tickets#edit</h1>
<%= simple_form_for @ticket do |f| %>
  <%= f.input :status %>
  <%= f.input :priority %>
  <%= f.input :category %>
  <%= f.button :submit %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Edit ticket</h1>
<%= simple_form_for @ticket do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <% if current_user.admin %>
    <%= f.input :user_id, collection: @users, hint: "Assign ticket to another users" %>
  <% end %>
  <%= f.input :status, collection: [['Open', 'open'], ['Closed', 'closed']] %>
  <%= f.input :priority , collection: [['Urgent', 'urgent'], ['Time sensitive', 'time_sensitive'], ['Necessary', 'necessary']] %>
  <%= f.input :category, collection: [['Front end', 'front_end'], ['Back end', 'back_end']] %>
  <%= f.button :submit, class: "btn btn-success button-custom" %>
<% end %>

app/views/tickets/index.html.erb
<h1>Tickets list
  <span class="button-link button-edit">
    <%= link_to new_ticket_path do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </span>
</h1>
<%= render 'shared/ticket_list', locals: { tickets: @tickets } %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>
  <%= simple_form_for @ticket do |f|%>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :priority , collection: [['Urgent', 'urgent'], ['Time sensitive', 'time_sensitive'], ['Necessary', 'necessary']] %>
  <%= f.input :project_id, collection: @projects%>
  <%= f.input :category %>
  <%= f.input :status %>
  <%= f.button :submit, class: "btn btn-success button-custom" %>
<% end %>

app/views/tickets/show.html.erb
<h1><%= @ticket.title %>
  <span class="button-link button-edit">
    <%= link_to edit_ticket_path(@ticket) do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </span>
</h1>
<div class="container-section container-ticket-data">
  <div class="container-ticket-description">
    <h2 class="header-margin-override">Statistics</h2>
    <div>
      <p>
        <span class="text-accent">
          Priority:&nbsp;
        </span>
        <%= @ticket.priority.capitalize %>
      </p>
      <p>
        <span class="text-accent">
          Ticket goals:&nbsp;
        </span>
        <%= @ticket.description %>
      </p>
      <p>
        <span class="text-accent">
          Worked hours:&nbsp;
        </span>
        <%= @ticket.working_time %>
      </p>
      <p>
        <span class="text-accent">
          Ticket owner:&nbsp;
          <%= link_to user_path(@ticket_user) do %>
            <%= "#{@ticket_user.first_name} #{@ticket_user.last_name}"%>
          <% end %>
        </span>
      </p>
    </div>
  </div>
  <div class="custom-container-hour-control">
    <div class="text-status">
      <% if @ticket.status == 'closed' %>
      Closed
      <% elsif @ticket.active %>
      Active
      <% else %>
      Not active
      <% end %>
    </div>
    <% unless @ticket.status == 'closed' %>
    <%= link_to update_hours_ticket_path(@ticket), method: :patch, remote: true do %>
    <div class="button-link button-hours">
      <% if @ticket.active %>
      <i class="fas fa-pause"></i>
      <% else %>
      <i class="fas fa-play"></i>
      <% end %>
    </div>
    <% end %>
    <div>
      <%= link_to "Close ticket", close_ticket_path(@ticket), class: "btn btn-danger button-custom" ,method: :patch, remote: true  %>
    </div>
    <% end %>
  </div>
</div>
<div class=" container-section container-ticket-memos">
  <div class="container-memo-list">
    <h2>Memo list</h2>
    <% @memos.each do |memo| %>
      <div class="container-memo-show ">
          <%= memo.content %>
         <span class="button-link button-edit">
          <%= link_to edit_ticket_memo_path(ticket_id: @ticket.id, id: memo.id) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </span>
        <br>
      </div>
    <% end %>
  </div>
  <div class="container-memo-new">
    <h2>Add new memo</h2>
    <%= render 'memos/new' %>
  </div>
</div>