config/routes.rb
Rails.application.routes.draw do
  get 'tickets/new'
  get 'tickets/edit'
  get 'tickets/show'
  get 'projects/new'
  get 'projects/edit'
  get 'projects/show'
  get 'projects/index'
  get 'pages/demo'
  get 'pages/guest'
  patch 'tickets/update_hours/:id' => "tickets#update_hours", as: :update_hours_ticket
  patch 'tickets/close_ticket/:id' => "tickets#close_ticket", as: :close_ticket

  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :events, only: [ :new, :edit, :index ]
  end
  resources :projects, only: [ :create, :edit, :update, :show, :index ] do
    resources :events, only: [ :new ]
  end
  resources :tickets, only: [ :new, :edit, :show, :index, :create, :update ] do
    resources :memos
    resources :events, only: [ :new, :create ]
  end
  resources :working_tickets, only: [ :show, :index ]
end

app/models/project.rb
class Project < ApplicationRecord
  include ActiveModel::Dirty

  has_many :tickets
  has_many :events, as: :eventable

  validates :name, :description, presence: true

  def identify_project_changes
    record = self.saved_changes
    changes = []
    changes << 'name' if record.has_key?('name')
    changes << 'status' if record.has_key?('active')
    changes << 'description' if record.has_key?('description')
    changes
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new

    authorize @project
  end

  def create
    @project = Project.new(create_params)
    @project.active = true

    authorize @project

    if @project.save
      event = Event.new(
              description: "Added project #{@project.name}",
              user: current_user,
              eventable: @project,
              link: "/projects/#{@project.id}"
              )
      event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])

    authorize @project
  end

  def update
    @project = Project.find(params[:id])

    authorize @project

    if @project.update(update_params)
      changes = Event.store_changes_record(@project.identify_project_changes)

      unless changes == "no changes"
        event = Event.new(
                  description: "Changed the #{changes} on project #{@project.name}",
                  user: current_user,
                  eventable: @project,
                  link: "/projects/#{@project.id}"
                )
        event.save
      end
      redirect_to projects_path
    else
      render :edit
    end
  end

  def show
    @project = Project.find(params[:id])
    @tickets = Ticket.where(project_id: @project, status: 'open')

    authorize @project
  end

  def index
    @projects = policy_scope(Project).order(created_at: :desc)
  end

  private

  def create_params
    params.require(:project).permit(:name, :description)
  end

  def update_params
    params.require(:project).permit(:active, :name, :description)
  end
end

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :active %>
  <%= f.button :submit, class: "btn btn-success button-custom" %>
<% end %>

app/views/projects/index.html.erb
<h1>Project list
  <% if current_user.admin %>
    <span class="button-link button-edit">
      <%= link_to projects_new_path do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </span>
  <% end %>
</h1>
<ul>
  <% @projects.each do |project| %>
    <li>
      <div class="container-clickable">
        <%= link_to project_path(project.id) do %>
        <h3 class="text-caps">
          <%= project.name %>
        </h3>
        <p>
          <%= project.description %>
        </p>
      <% end %>
      </div>
     </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= simple_form_for @project do |f| %>
  <%= f.input :name, hint: "If the project name has multiple words separate them with _" %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-success button-custom" %>
<% end %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
  <span class="button-link button-edit">
    <%= link_to edit_project_path(@project) do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </span>
</h1>
<div class="container-section">
  <p class="text-project-description"><%= @project.description %></p>
</div>
<h2>Project tickets
  <% unless @tickets.empty? %>
    <span class="button-link button-edit">
    <%= link_to new_ticket_path do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </span>
  <% end %>
</h2>
<% if @tickets.empty? %>
  <%= link_to "Add a new ticket", new_ticket_path, class: "link-nav" %>
<% else %>
  <%= render 'shared/ticket_list', locals: { tickets: @user_tickets } %>
<% end %>