config/routes.rb
Rails.application.routes.draw do
  get 'tickets/new'
  get 'tickets/edit'
  get 'tickets/show'
  get 'projects/new'
  get 'projects/edit'
  get 'projects/show'
  get 'projects/index'
  get 'pages/demo'
  get 'pages/guest'
  patch 'tickets/update_hours/:id' => "tickets#update_hours", as: :update_hours_ticket
  patch 'tickets/close_ticket/:id' => "tickets#close_ticket", as: :close_ticket

  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :events, only: [ :new, :edit, :index ]
  end
  resources :projects, only: [ :create, :edit, :update, :show, :index ] do
    resources :events, only: [ :new ]
  end
  resources :tickets, only: [ :new, :edit, :show, :index, :create, :update ] do
    resources :memos
    resources :events, only: [ :new, :create ]
  end
  resources :working_tickets, only: [ :show, :index ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
  has_many :tickets, through: :tickets_users
  has_many :user_events
  has_many :events, as: :eventable
  has_one :working_ticket

  validates :first_name, :last_name, presence: true
  validates :email, :employee_number, uniqueness: true, presence: true

end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  skip_before_action :require_no_authentication, only: [:new]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite,
                                      keys: [
                                      :first_name,
                                      :last_name,
                                      :employee_number,
                                      :admin
                                      ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @events = Event.where(user: @user).order('created_at DESC')
    @tickets = Ticket.where(user_id: @user, status: 'open')

    authorize @user
  end

  def new
    user = User.new

    authorize current_user
  end

  def create
    user = User.new(user_params, active: true)

    authorize current_user

    if user.save
      if user_signed_in?
        event = UserEvent.new(
                  description: "Created user #{user.first_name} #{user.last_name}",
                  user: current_user,
                  link: "/user/#{user.id}"
                )
        event.save
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(params[:id])
    else
      render :edit
    end
  end

  def index
    @users = policy_scope(User).order(created_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name,
      :supervisor, :email, :employee_number)
  end
end

app/views/users/invitations/edit.html.erb
<h2><%= t "devise.invitations.edit.header" %></h2>

<%= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :invitation_token %>

  <div class="form-inputs">
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t("devise.invitations.edit.submit_button") %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= f.error_notification %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="form-inputs">
      <%= f.input field %>
    </div>
  <% end -%>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :employee_number %>
  <%= f.input :admin, inline_label: 'Administrator' %>

  <div class="form-actions">
    <%= f.button :submit, t("devise.invitations.new.submit_button") %>
  </div>
<% end %>